# Generated by Django 6.1.1 on 2026-10-02 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='دسته بندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به روزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دوره')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=15, verbose_name='سطح دوره')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('is_published', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار دوره')),
                ('can_sale', models.BooleanField(default=True, verbose_name='قابل فروش؟')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='(ریال)قیمت دوره')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='course-posters/', verbose_name='عکس شاخص')),
                ('intro_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='ویدئو معرفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('requirements', models.ManyToManyField(blank=True, related_name='required_by_courses', to='course.course', verbose_name='پیش\u200cنیازها')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teached_courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('categories', models.ManyToManyField(related_name='courses', to='course.coursecategory', verbose_name='دسته\u200cبندی\u200cها')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان فصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات فصل')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='course.course', verbose_name='دوره')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('title', models.CharField(max_length=25, verbose_name='عنوان جلسه')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان')),
                ('video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس ویدئو')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='course-session-posters/', verbose_name='عکس شاخص')),
                ('source_code', models.FileField(blank=True, null=True, upload_to='course-source-codes/', verbose_name='سورس کد های جلسه')),
                ('has_homework', models.BooleanField(verbose_name='جلسه دارای تمرین؟')),
                ('is_public', models.BooleanField(default=False, verbose_name='جلسه عمومی؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.courseseason', verbose_name='فصل')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='آخرین موقعیت پخش به میلی\u200cثانیه')),
                ('max_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='بیشترین موقعیت مشاهده\u200cشده')),
                ('unique_watched_ms', models.PositiveBigIntegerField(default=0, verbose_name='زمان مشاهده یکتا')),
                ('total_watched_ms', models.PositiveBigIntegerField(default=0, verbose_name='کل زمان مشاهده')),
                ('watch_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات مشاهده')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات پخش')),
                ('last_watched_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین مشاهده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل جلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='course.coursesession', verbose_name='جلسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_session_progresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionWatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='موقعیت شروع')),
                ('last_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='آخرین موقعیت')),
                ('max_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='بیشترین موقعیت')),
                ('watched_ms', models.PositiveBigIntegerField(default=0, verbose_name='زمان مشاهده در این نوبت')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع مشاهده')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان مشاهده')),
                ('end_reason', models.CharField(blank=True, choices=[('ended', 'پایان ویدئو'), ('navigation', 'خروج کاربر'), ('inactivity', 'عدم فعالیت'), ('error', 'خطای پخش'), ('unknown', 'نامشخص')], max_length=20, verbose_name='دلیل پایان مشاهده')),
                ('auth_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_watches', to='user.authsession', verbose_name='نشست کاربر')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='course.coursesessionprogress', verbose_name='پیشرفت')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionWatchedRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ms', models.PositiveBigIntegerField(verbose_name='شروع بازه')),
                ('end_ms', models.PositiveBigIntegerField(verbose_name='پایان بازه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_ranges', to='course.coursesessionprogress', verbose_name='پیشرفت')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='شماره ترتیب رویداد')),
                ('client_event_id', models.UUIDField(unique=True, verbose_name='شناسه رویداد سمت کلاینت')),
                ('event_type', models.CharField(choices=[('play', 'پخش'), ('pause', 'توقف'), ('seek', 'جابجایی'), ('heartbeat', 'ادامه مشاهده'), ('ended', 'پایان'), ('rate_change', 'تغییر سرعت'), ('error', 'خطا')], max_length=20, verbose_name='نوع رویداد')),
                ('position_ms', models.PositiveBigIntegerField(verbose_name='موقعیت ویدئو')),
                ('from_position_ms', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='موقعیت قبل')),
                ('to_position_ms', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='موقعیت بعد')),
                ('playback_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='سرعت پخش')),
                ('client_occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رویداد در کلاینت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دریافت در سرور')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='course.coursesessionwatch', verbose_name='مشاهده')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseseason',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_course_season_order'),
        ),
        migrations.AddConstraint(
            model_name='coursesession',
            constraint=models.UniqueConstraint(fields=('season', 'order'), name='unique_season_session_order'),
        ),
        migrations.AddIndex(
            model_name='coursesessionprogress',
            index=models.Index(fields=['user', '-last_watched_at'], name='course_progress_user_last_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesessionprogress',
            constraint=models.UniqueConstraint(fields=('user', 'session'), name='unique_user_session_progress'),
        ),
        migrations.AddIndex(
            model_name='coursesessionwatch',
            index=models.Index(fields=['progress', '-started_at'], name='course_watch_progress_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesessionwatchedrange',
            index=models.Index(fields=['progress', 'start_ms', 'end_ms'], name='course_watched_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesessionwatchedrange',
            constraint=models.CheckConstraint(condition=models.Q(('end_ms__gt', models.F('start_ms'))), name='watched_range_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='coursesessionwatchevent',
            index=models.Index(fields=['watch', 'created_at'], name='course_watch_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesessionwatchevent',
            constraint=models.UniqueConstraint(fields=('watch', 'sequence'), name='unique_watch_event_sequence'),
        ),
    ]
