# Generated by Django 6.1.1 on 2026-10-04 06:55

import course.models
import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='دسته بندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به روزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان فصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات فصل')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('title', models.CharField(max_length=25, verbose_name='عنوان جلسه')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان')),
                ('video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس ویدئو')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=course.models.session_poster_upload_to, verbose_name='عکس شاخص')),
                ('source_code', models.FileField(blank=True, null=True, upload_to='course-source-codes/', verbose_name='سورس کد های جلسه')),
                ('has_homework', models.BooleanField(verbose_name='جلسه دارای تمرین؟')),
                ('is_public', models.BooleanField(default=False, verbose_name='جلسه عمومی؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionHomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=course.models.homework_submission_upload_to)),
                ('status', models.CharField(choices=[('submitted', 'ارسال شده'), ('reviewed', 'بررسی شده')], default='submitted', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('review_homework_submission', 'Can review homework submission')],
            },
        ),
        migrations.CreateModel(
            name='CourseSessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='آخرین موقعیت پخش به میلی\u200cثانیه')),
                ('max_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='بیشترین موقعیت مشاهده\u200cشده')),
                ('unique_watched_ms', models.PositiveBigIntegerField(default=0, verbose_name='زمان مشاهده یکتا')),
                ('total_watched_ms', models.PositiveBigIntegerField(default=0, verbose_name='کل زمان مشاهده')),
                ('watch_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات مشاهده')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات پخش')),
                ('last_watched_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین مشاهده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل جلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionWatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='موقعیت شروع')),
                ('last_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='آخرین موقعیت')),
                ('max_position_ms', models.PositiveBigIntegerField(default=0, verbose_name='بیشترین موقعیت')),
                ('watched_ms', models.PositiveBigIntegerField(default=0, verbose_name='زمان مشاهده در این نوبت')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع مشاهده')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان مشاهده')),
                ('end_reason', models.CharField(blank=True, choices=[('ended', 'پایان ویدئو'), ('navigation', 'خروج کاربر'), ('inactivity', 'عدم فعالیت'), ('error', 'خطای پخش'), ('unknown', 'نامشخص')], max_length=20, verbose_name='دلیل پایان مشاهده')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionWatchedRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ms', models.PositiveBigIntegerField(verbose_name='شروع بازه')),
                ('end_ms', models.PositiveBigIntegerField(verbose_name='پایان بازه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='شماره ترتیب رویداد')),
                ('client_event_id', models.UUIDField(unique=True, verbose_name='شناسه رویداد سمت کلاینت')),
                ('event_type', models.CharField(choices=[('play', 'پخش'), ('pause', 'توقف'), ('seek', 'جابجایی'), ('heartbeat', 'ادامه مشاهده'), ('ended', 'پایان'), ('rate_change', 'تغییر سرعت'), ('error', 'خطا')], max_length=20, verbose_name='نوع رویداد')),
                ('position_ms', models.PositiveBigIntegerField(verbose_name='موقعیت ویدئو')),
                ('from_position_ms', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='موقعیت قبل')),
                ('to_position_ms', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='موقعیت بعد')),
                ('playback_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='سرعت پخش')),
                ('client_occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رویداد در کلاینت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دریافت در سرور')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
            ],
        ),
        migrations.CreateModel(
            name='GiftVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('player_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس پلیر')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=course.models.gift_poster_upload_to, verbose_name='کاور')),
                ('duration', models.DurationField(default=datetime.timedelta, verbose_name='مدت زمان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دوره')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=15, verbose_name='سطح دوره')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('is_published', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار دوره')),
                ('can_sale', models.BooleanField(default=True, verbose_name='قابل فروش؟')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='(ریال)قیمت دوره')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=course.models.course_poster_upload_to, verbose_name='عکس شاخص')),
                ('intro_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='ویدئو معرفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('requirements', models.ManyToManyField(blank=True, related_name='required_by_courses', to='course.course', verbose_name='پیش\u200cنیازها')),
            ],
            options={
                'permissions': [('publish_course', 'Can publish course'), ('view_own_course_sales', 'Can view own course sales'), ('view_own_course_commission', 'Can view own course commission'), ('view_teacher_sales_ranking', 'Can view teacher sales ranking'), ('view_all_courses', 'Can view all courses'), ('change_any_course', 'Can change any course'), ('view_own_courses', 'Can view own courses')],
            },
        ),
    ]
