# Generated by Django 6.1.1 on 2026-10-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('publish_course', 'Can publish course'), ('view_own_course_sales', 'Can view own course sales'), ('view_own_course_commission', 'Can view own course commission'), ('view_teacher_sales_ranking', 'Can view teacher sales ranking')]},
        ),
    ]
