# Generated by Django 6.1.1 on 2026-10-04 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teached_courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس'),
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(related_name='courses', to='course.coursecategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AddField(
            model_name='courseseason',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='course.course', verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.courseseason', verbose_name='فصل'),
        ),
        migrations.AddField(
            model_name='coursesessionhomeworksubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_homework_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesessionhomeworksubmission',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to='course.coursesession'),
        ),
        migrations.AddField(
            model_name='coursesessionhomeworksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesessionprogress',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='course.coursesession', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='coursesessionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_session_progresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='coursesessionwatch',
            name='auth_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_watches', to='user.authsession', verbose_name='نشست کاربر'),
        ),
        migrations.AddField(
            model_name='coursesessionwatch',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='course.coursesessionprogress', verbose_name='پیشرفت'),
        ),
        migrations.AddField(
            model_name='coursesessionwatchedrange',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_ranges', to='course.coursesessionprogress', verbose_name='پیشرفت'),
        ),
        migrations.AddField(
            model_name='coursesessionwatchevent',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='course.coursesessionwatch', verbose_name='مشاهده'),
        ),
        migrations.AddConstraint(
            model_name='courseseason',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_course_season_order'),
        ),
        migrations.AddConstraint(
            model_name='coursesession',
            constraint=models.UniqueConstraint(fields=('season', 'order'), name='unique_season_session_order'),
        ),
        migrations.AddIndex(
            model_name='coursesessionhomeworksubmission',
            index=models.Index(fields=['student', '-updated_at'], name='course_cour_student_6099fb_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesessionhomeworksubmission',
            index=models.Index(fields=['session', 'status'], name='course_cour_session_d4845e_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesessionhomeworksubmission',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_student_session_homework'),
        ),
        migrations.AddIndex(
            model_name='coursesessionprogress',
            index=models.Index(fields=['user', '-last_watched_at'], name='course_progress_user_last_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesessionprogress',
            constraint=models.UniqueConstraint(fields=('user', 'session'), name='unique_user_session_progress'),
        ),
        migrations.AddIndex(
            model_name='coursesessionwatch',
            index=models.Index(fields=['progress', '-started_at'], name='course_watch_progress_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesessionwatchedrange',
            index=models.Index(fields=['progress', 'start_ms', 'end_ms'], name='course_watched_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesessionwatchedrange',
            constraint=models.CheckConstraint(condition=models.Q(('end_ms__gt', models.F('start_ms'))), name='watched_range_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='coursesessionwatchevent',
            index=models.Index(fields=['watch', 'created_at'], name='course_watch_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesessionwatchevent',
            constraint=models.UniqueConstraint(fields=('watch', 'sequence'), name='unique_watch_event_sequence'),
        ),
    ]
