# Generated by Django 6.1.1 on 2026-10-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('publish_course', 'Can publish course'), ('view_own_course_sales', 'Can view own course sales'), ('view_own_course_commission', 'Can view own course commission'), ('view_teacher_sales_ranking', 'Can view teacher sales ranking'), ('view_all_courses', 'Can view all courses'), ('change_any_course', 'Can change any course')]},
        ),
    ]
