# Generated by Django 6.1.1 on 2026-10-03 05:50

import course.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSessionHomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=course.models.homework_submission_upload_to)),
                ('status', models.CharField(choices=[('submitted', 'ارسال شده'), ('reviewed', 'بررسی شده')], default='submitted', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_homework_submissions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to='course.coursesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('review_homework_submission', 'Can review homework submission')],
                'indexes': [models.Index(fields=['student', '-updated_at'], name='course_cour_student_6099fb_idx'), models.Index(fields=['session', 'status'], name='course_cour_session_d4845e_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_student_session_homework')],
            },
        ),
    ]
