# Generated by Django 6.1.1 on 2026-10-06 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_persian_verbose_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftVideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watch_token",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="شناسهٔ نوبت تماشا",
                    ),
                ),
                (
                    "watched_ranges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="بازه\u200cهای دیده\u200cشده",
                    ),
                ),
                (
                    "unique_watched_ms",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="زمان مشاهدهٔ یکتا (ms)"
                    ),
                ),
                (
                    "last_position_ms",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="آخرین موقعیت (ms)"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین فعالیت"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تکمیل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="course.giftvideo",
                        verbose_name="ویدئوی هدیه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشرفت ویدئوی هدیه",
                "verbose_name_plural": "پیشرفت ویدئوهای هدیه",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "gift"), name="unique_gift_progress"
                    )
                ],
            },
        ),
    ]
