# Generated by Django 6.1.1 on 2026-10-03 20:19

import course.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursesessionhomeworksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('player_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس پلیر')),
                ('cover', models.CharField(blank=True, max_length=255, null=True, verbose_name='کاور')),
                ('duration', models.DurationField(default=datetime.timedelta, verbose_name='مدت زمان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.course_poster_upload_to, verbose_name='عکس شاخص'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.session_poster_upload_to, verbose_name='عکس شاخص'),
        ),
    ]
