# Generated by Django 6.1.1 on 2026-10-03 20:31

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_giftvideo_alter_course_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvideo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.gift_poster_upload_to, verbose_name='کاور'),
        ),
    ]
