# Generated by Django 6.1.1 on 2026-10-08 12:26

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_gift_video_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftvideoprogress",
            name="watch_credited_ms",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="زمان ثبت\u200cشده در نوبت فعلی (ms)"
            ),
        ),
        migrations.AddField(
            model_name="giftvideoprogress",
            name="watch_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="شروع نوبت تماشا"
            ),
        ),
        migrations.AlterField(
            model_name="coursesessionhomeworksubmission",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=course.models.private_media_storage,
                upload_to=course.models.homework_submission_upload_to,
            ),
        ),
    ]
