# Generated by Django 6.1.1 on 2026-10-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPSMSToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('login', 'ورود'), ('reset_pass', 'بازنشانی گذرواژه'), ('mobile_verify', 'تایید شماره موبایل')], max_length=20, verbose_name='دلیل درخواست کد')),
                ('code_hash', models.CharField(max_length=128, verbose_name='کد هش شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضاء کد')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده از کد')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ابطال')),
            ],
        ),
        migrations.CreateModel(
            name='SMSServerResponse',
            fields=[
                ('text', models.CharField(max_length=255, verbose_name='متن ارسالی')),
                ('recipient', models.CharField(max_length=11, verbose_name='دریافت کننده')),
                ('trace_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('rejected', 'عدم ارسال'), ('failed', 'خطا'), ('timeout', 'تایم اوت'), ('requested', 'درخواست به سرویس دهنده')], default='pending', max_length=10, verbose_name='وضعیت ارسال')),
                ('server_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ سرور اس ام اس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییر')),
            ],
        ),
    ]
