# Generated by Django 6.1.1 on 2026-10-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsserverresponse',
            name='trace_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='کد پیگیری'),
        ),
    ]
