# Generated by Django 6.1.1 on 2026-10-06 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("course", "0006_gift_video_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="لینک (اختیاری)"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "همهٔ کاربران"),
                            ("groups", "گروه\u200cهای انتخاب\u200cشده"),
                            ("users", "افراد مشخص"),
                            (
                                "course_students",
                                "خریداران دوره\u200cهای انتخاب\u200cشده",
                            ),
                            ("mentees", "دانشجوهای یک منتور"),
                        ],
                        max_length=20,
                        verbose_name="مخاطب",
                    ),
                ),
                (
                    "send_sms",
                    models.BooleanField(default=False, verbose_name="ارسال پیامک"),
                ),
                (
                    "sender_label",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="نام فرستنده برای گیرنده",
                    ),
                ),
                (
                    "recipient_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد گیرندگان"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="announcements",
                        to="course.course",
                        verbose_name="دوره\u200cها",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فرستنده",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="announcements",
                        to="auth.group",
                        verbose_name="گروه\u200cها",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منتور (برای «دانشجوهای یک منتور»)",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="افراد",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ("-created_at",),
                "permissions": [
                    ("send_announcement_all", "Can send announcement to all users"),
                    ("send_announcement_groups", "Can send announcement to any groups"),
                    (
                        "send_announcement_users",
                        "Can send announcement to specific users",
                    ),
                    (
                        "send_announcement_course_students",
                        "Can send announcement to own course students",
                    ),
                    (
                        "send_announcement_any_course",
                        "Can send announcement to students of any course",
                    ),
                    (
                        "send_announcement_mentees",
                        "Can send announcement to own mentees",
                    ),
                    (
                        "send_announcement_any_mentor",
                        "Can send announcement to mentees of any mentor",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sms_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="اعضای این گروه\u200cها هنگام ارسال اعلان می\u200cتوانند «ارسال پیامک» را هم انتخاب کنند. مدیر اصلی (superuser) همیشه اجازه دارد.",
                        related_name="+",
                        to="auth.group",
                        verbose_name="گروه\u200cهایی که اجازهٔ ارسال پیامک دارند",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات اعلان\u200cها",
                "verbose_name_plural": "تنظیمات اعلان\u200cها",
            },
        ),
        migrations.CreateModel(
            name="AnnouncementRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان خواندن"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان دریافت"),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="announcement.announcement",
                        verbose_name="اعلان",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_inbox",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "گیرندهٔ اعلان",
                "verbose_name_plural": "گیرندگان اعلان",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="announcement_inbox_idx"
                    ),
                    models.Index(
                        fields=["user", "read_at"], name="announcement_unread_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("announcement", "user"),
                        name="unique_announcement_recipient",
                    )
                ],
            },
        ),
    ]
