# Generated by Django 6.1.1 on 2026-10-06 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(
                        max_length=1000, unique=True, verbose_name="آدرس سرویس push"
                    ),
                ),
                (
                    "p256dh",
                    models.CharField(max_length=200, verbose_name="کلید p256dh"),
                ),
                ("auth", models.CharField(max_length=100, verbose_name="کلید auth")),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=300, verbose_name="مرورگر"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین ارسال موفق"
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="خطاهای پشت\u200cسرهم"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراک نوتیفیکیشن گوشی",
                "verbose_name_plural": "اشتراک\u200cهای نوتیفیکیشن گوشی",
            },
        ),
    ]
