# Generated by Django 6.1.1 on 2026-10-06 09:48

import course.models
import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0005_persian_verbose_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, unique=True, verbose_name="عنوان"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "فناوری",
                "verbose_name_plural": "فناوری\u200cها",
                "ordering": ("order", "title"),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("aiohoush", "پروژهٔ آیوهوش"),
                            ("student", "پروژهٔ دانشجو"),
                        ],
                        default="aiohoush",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("github_url", models.URLField(blank=True, verbose_name="لینک GitHub")),
                ("demo_url", models.URLField(blank=True, verbose_name="لینک دمو")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تأیید"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="دلیل رد"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال برای بررسی"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف شده"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان حذف"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="course.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دانشجو",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بررسی\u200cکننده",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="project.technology",
                        verbose_name="فناوری\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
                "ordering": ("-created_at",),
                "permissions": [
                    ("review_project", "Can approve or reject student projects"),
                    ("view_project_files", "Can download files of any project"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=course.models.private_media_storage,
                        upload_to=project.models.project_file_upload_to,
                        verbose_name="فایل",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="نام اصلی فایل"),
                ),
                ("size", models.PositiveBigIntegerField(verbose_name="حجم (بایت)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان آپلود"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="project.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل پروژه",
                "verbose_name_plural": "فایل\u200cهای پروژه",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=project.models.project_image_upload_to,
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان آپلود"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="project.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر پروژه",
                "verbose_name_plural": "تصاویر پروژه",
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["kind", "status", "-created_at"], name="project_gallery_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "student"), _negated=True),
                    ("owner__isnull", False),
                    _connector="OR",
                ),
                name="student_project_has_owner",
            ),
        ),
    ]
