# Generated by Django 6.1.1 on 2026-10-01 21:20

import aiohoush.utilities.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[aiohoush.utilities.validators.mobile_validator], verbose_name='شماره موبایل')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[aiohoush.utilities.validators.national_id_validator], verbose_name='کد ملی')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین پنل؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('is_mobile_verified', models.BooleanField(default=False, verbose_name='موبایل تایید شده است؟')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد؟')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییر')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس پستی')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[aiohoush.utilities.validators.postal_code_validator], verbose_name='کد پستی')),
                ('denied_permissions', models.ManyToManyField(blank=True, help_text='این مجوزها حتی در صورت دریافت از گروه یا مجوز مستقیم ممنوع هستند. روی superuser فعال اثری ندارند.', related_name='users_denied_permission', to='auth.permission', verbose_name='مجوزهای ممنوع\u200cشده')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(max_length=255, unique=True, verbose_name='شناسه Refresh Token فعلی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('browser_name', models.CharField(blank=True, max_length=100, verbose_name='نام مرورگر')),
                ('browser_version', models.CharField(blank=True, max_length=100, verbose_name='نسخه مرورگر')),
                ('os_name', models.CharField(blank=True, max_length=100, verbose_name='سیستم عامل')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='نسخه سیستم عامل')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='نوع دستگاه')),
                ('device_brand', models.CharField(blank=True, max_length=100, verbose_name='برند دستگاه')),
                ('device_model', models.CharField(blank=True, max_length=150, verbose_name='مدل دستگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین استفاده')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ابطال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد معرف')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان کد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد کد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن کد')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_referral_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_users', to='user.referralcode', verbose_name='کد معرف هنگام ثبت نام'),
        ),
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profilepictures/', verbose_name='عکس پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگزاری')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pictures', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='علت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mentor_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر متصل کننده')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentored_students_history', to=settings.AUTH_USER_MODEL, verbose_name='منتور')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('student', models.F('mentor')), _negated=True), name='student_mentor_must_differ'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='unique_active_mentor_per_student'), models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('is_active', True)), models.Q(('ended_at__isnull', False), ('is_active', False)), _connector='OR'), name='mentor_assignment_status_matches_end', violation_error_message='تخصیص فعال نباید تاریخ پایان داشته باشد؛ تخصیص پایان\u200cیافته باید تاریخ پایان داشته باشد.'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='mentor_assignment_end_after_start', violation_error_message='تاریخ پایان نمی\u200cتواند قبل از تاریخ شروع باشد.')],
            },
        ),
    ]
