# Generated by Django 6.1.1 on 2026-10-04 04:26

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False, verbose_name='پروفایل تکمیل شده است؟'),
        ),
        migrations.AlterField(
            model_name='userprofilepicture',
            name='picture',
            field=models.ImageField(upload_to=user.models.user_avatar_upload_to, verbose_name='عکس پروفایل'),
        ),
    ]
