# Generated by Django 6.1.1 on 2026-10-01 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('browser_name', models.CharField(blank=True, max_length=100, verbose_name='نام مرورگر')),
                ('browser_version', models.CharField(blank=True, max_length=100, verbose_name='نسخه مرورگر')),
                ('os_name', models.CharField(blank=True, max_length=100, verbose_name='سیستم عامل')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='نسخه سیستم عامل')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='نوع دستگاه')),
                ('device_brand', models.CharField(blank=True, max_length=100, verbose_name='برند دستگاه')),
                ('device_model', models.CharField(blank=True, max_length=150, verbose_name='مدل دستگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین استفاده')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ابطال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
