# Generated by Django 6.1.1 on 2026-10-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('saderat', 'صادرات'), ('sepah', 'سپه'), ('melli', 'ملی')], max_length=10, verbose_name='نام بانک')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('sheba', models.CharField(max_length=24, verbose_name='شماره شبا')),
                ('account_number', models.CharField(max_length=24, verbose_name='شماره حساب')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ واریزی')),
                ('paid_at', models.DateTimeField(verbose_name='تاریخ واریز')),
                ('tracking_code', models.CharField(max_length=255, verbose_name='کد پیگیری')),
                ('gateway', models.CharField(choices=[('zibal', 'زیبال'), ('zarinpal', 'زرینپال'), ('transfer', 'انتقال')], max_length=10, verbose_name='درگاه')),
                ('user_card_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='چهار رقم آخر کارت کاربر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده؟')),
            ],
        ),
    ]
