# Generated by Django 6.1.1 on 2026-10-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('saderat', 'صادرات'), ('sepah', 'سپه'), ('melli', 'ملی')], max_length=10, verbose_name='نام بانک')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('sheba', models.CharField(max_length=24, verbose_name='شماره شبا')),
                ('account_number', models.CharField(max_length=24, verbose_name='شماره حساب')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='صاحب حساب')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ واریزی')),
                ('paid_at', models.DateTimeField(verbose_name='تاریخ واریز')),
                ('tracking_code', models.CharField(max_length=255, verbose_name='کد پیگیری')),
                ('gateway', models.CharField(choices=[('zibal', 'زیبال'), ('zarinpal', 'زرینپال'), ('transfer', 'انتقال')], max_length=10, verbose_name='درگاه')),
                ('user_card_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='چهار رقم آخر کارت کاربر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده؟')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='accounting.bankaccount', verbose_name='حساب دریافت کننده')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
        ),
    ]
