# Generated by Django 6.1.1 on 2026-10-04 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه سفارش محصول هوش مصنوعی')),
                ('product_code', models.CharField(max_length=80, verbose_name='کد محصول')),
                ('amount_rial', models.PositiveBigIntegerField(verbose_name='مبلغ سفارش (ریال)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('videopol_payment_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه پرداخت ویدوپول')),
                ('payment_url', models.URLField(blank=True, verbose_name='آدرس پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه مرجع پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('draft', 'پیش نویس')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='پاک شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'permissions': [('approve_order', 'Can approve order'), ('reject_order', 'Can reject order'), ('view_own_sales_report', 'Can view own sales report'), ('view_own_sales_commission', 'Can view own sales commission'), ('view_all_orders', 'Can view all orders'), ('change_any_order', 'Can change any order')],
            },
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='توضیح سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ دوره هنگام ثبت سفارش')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='تخفیف')),
            ],
        ),
    ]
