# Generated by Django 6.1.1 on 2026-10-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('draft', 'پیش نویس')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='پاک شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بررسی کننده')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده سفارش')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='توضیح سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر کامنت دهنده')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ دوره هنگام ثبت سفارش')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='تخفیف')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_products', to='course.course', verbose_name='دوره')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_products', to='order.order', verbose_name='سفارش')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'course'), name='unique_course_per_order'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='requested_product_price_gte_0'), models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='requested_product_discount_gte_0'), models.CheckConstraint(condition=models.Q(('discount__lte', models.F('price'))), name='requested_product_discount_lte_price')],
            },
        ),
    ]
