# Generated by Django 6.1.1 on 2026-10-04 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproductorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_product_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='order',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بررسی کننده'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='ordercomment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='ordercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر کامنت دهنده'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_products', to='course.course', verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_products', to='order.order', verbose_name='سفارش'),
        ),
        migrations.AddConstraint(
            model_name='requestedproduct',
            constraint=models.UniqueConstraint(fields=('order', 'course'), name='unique_course_per_order'),
        ),
        migrations.AddConstraint(
            model_name='requestedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='requested_product_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='requestedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='requested_product_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='requestedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('price'))), name='requested_product_discount_lte_price'),
        ),
    ]
