# Generated by Django 6.1.1 on 2026-10-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('approve_order', 'Can approve order'), ('reject_order', 'Can reject order'), ('view_own_sales_report', 'Can view own sales report'), ('view_own_sales_commission', 'Can view own sales commission'), ('view_all_orders', 'Can view all orders'), ('change_any_order', 'Can change any order')]},
        ),
    ]
