# Generated by Django 6.1.1 on 2026-10-04 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه سفارش محصول هوش مصنوعی')),
                ('product_code', models.CharField(max_length=80, verbose_name='کد محصول')),
                ('amount_rial', models.PositiveBigIntegerField(verbose_name='مبلغ سفارش (ریال)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('videopol_payment_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه پرداخت ویدوپول')),
                ('payment_url', models.URLField(blank=True, verbose_name='آدرس پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه مرجع پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_product_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
